### ISSUE TITLE
Use correct account

### ISSUE THREAD

**Issue by DamienCassou** [egh/ledger-autosync#56] opened 2018-08-07 10:20 UTC
The way ledger-autosync decides which account to use doesn't suit my needs. This is because of automated transactions.

Here is my ledger file (also available as attachement):

```ledger
= /Expenses/
    [Assets:Budget:Unbudgeted]                  -1.0
    [Equity:Budget]                              1.0

= /Expenses:Something/
    [Assets:Budget:Something]                   -1.0
    [Assets:Budget:Unbudgeted]                   1.0

2018/08/06 Some guy
    Assets:Current:Damien                     -10.00 EUR
    Expenses:Something                         10.00 EUR
```

If you import an ofx file referencing "Some guy", you will get:

```ledger
2018/07/30 Some guy
    Assets:Current                                     -20.00 EUR
    [Assets:Budget:Unbudgeted]                          20.00 EUR
```

Here, I don't want `[Assets:Budget:Unbudgeted]` (which is an implementation detail) but `Expenses:Something` (which is what I already wrote in the existing ledger file).

Reproduce this with these attachments:

- [foo.ledger.txt](https://github.com/egh/ledger-autosync/files/2265978/foo.ledger.txt)
- [foo.ofx.txt](https://github.com/egh/ledger-autosync/files/2265979/foo.ofx.txt)

and this command line:

```shell
> ledger-autosync --ledger foo.ledger --payee-format "{payee}" --account Assets:Current --fid 000 foo.ofx
```

**Comment by DamienCassou** [comment] 2018-08-07 10:41
Currently the matching accounts are found by asking ledger for all accounts in relation with a payee. This is a problem because ledger returns automatic postings (those that are not in the ledger file). Because ledger-autosync output is supposed to be written in the ledger file, I expect it to ignore postings that are not already written in the ledger file.

One way to solve this issue would be to look inside the ledger file instead of asking ledger to do that.

**Comment by DamienCassou** [comment] 2018-08-07 10:57
Current workaround

```diff
--- /home/cassou/.local/venvs/ledger-autosync/lib/python3.6/site-packages/ledgerautosync/ledgerwrap.orig.py	2018-08-07 12:56:21.059177160 +0200
+++ /home/cassou/.local/venvs/ledger-autosync/lib/python3.6/site-packages/ledgerautosync/ledgerwrap.py	2018-08-07 12:53:02.225141519 +0200
@@ -80,7 +80,10 @@
     def filter_accounts(self, accts, exclude):
         accts_filtered = [a for a in accts if a != exclude]
         if accts_filtered:
-            return accts_filtered[-1]
+            pattern = re.compile("^Expenses:")
+            return next(filter(lambda account: pattern.match(account),
+                               accts_filtered),
+                        accts_filtered[-1])
         else:
             return None
 ```

**Comment by 501st-alpha1** [comment] 2018-08-07 16:44
I run into this same issue occasionally.  (Due to #25 it's not very often, but once that is fixed I will probably see it more.)

This could be fixed by adding the `--actual` flag to the command that looks up these accounts.  From [the docs](https://www.ledger-cli.org/3.0/doc/ledger3.html#Report-filtering):

```
--actual
-L
    Display only actual postings, and not those created by automated transactions.
```

**Comment by DamienCassou** [comment] 2020-02-11 08:09
This bug still annoys me :-).

**Comment by egh** [comment] 2020-02-11 14:03
I guess https://github.com/egh/ledger-autosync/pull/77 did not fix the issue?

**Comment by 501st-alpha1** [comment] 2020-02-13 20:00
I can confirm that this still happens for me on latest `master`, so #77 didn't fix the issue.  Looking at the PR again, it looks like the change was only made for the HLedger interface, not the raw Ledger interface (which I use) or `LedgerPython`.

**Comment by 501st-alpha1** [comment] 2020-02-13 23:26
Opened #96 to fix the raw Ledger interface.  I'm not familiar enough with the `LedgerPython` interface to know if / how to apply the fix there.

**Closed** 2020-02-14 07:02 UTC
